name: Build and Test Workflow
on: 
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build Debug
        run: dotnet build RestoringHP/RestoringHP.csproj --configuration Debug
   
  build-release:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build Debug
        run: dotnet build RestoringHP/RestoringHP.csproj --configuration Release
  
  test-debug:
    needs: build-debug
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run debug tests
        run: dotnet build RestoringHPTesting/RestoringHPTesting.csproj

  analyze:
    needs: build-debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Analyze code
        run: dotnet tool install -g dotnet-format && dotnet format RestoringHP/RestoringHP.csproj

  test-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run release tests
        run: dotnet build RestoringHPTesting/RestoringHPTesting.csproj
