name: Build and Artifacts
on: 
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build RestoringHP/RestoringHP.csproj --configuration ${{matrix.configuration}}
  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Get artifacts
        uses: actions/upload-artifact@v4
        with:
          name:  MyArtifact ${{matrix.configuration}}   
          path: RestoringHP/bin/${{matrix.configuration}}/